#!/usr/bin/python3

    farenheit =int (input("Farenheit to Celsius, type the Farenheit:"))
    celsius =(farenheit-32)*5//9
    print(celsius)
    #This was coded this way to know the variable of the temperature in diffrent locations.
    
